name: Cache Refresh
on:
  schedule:
    - cron: '0 2 */5 * *'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  Cache-Refresh:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Refresh cache with dependencies download
        run: ./gradlew dependencies
      - name: Stop Gradle daemon
        run: ./gradlew --stop